# Generated by Django 5.2 on 2025-05-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_propertybook_childern_alter_propertybook_guest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyreview',
            options={'ordering': ['created_at']},
        ),
    ]
