# Generated by Django 5.2 on 2025-05-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_propertyreview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
